from enum import Enum


class SID(Enum):
    UP = 0
    RIGHT = 1
    DOWN = 2
    LEFT = 3


ICON_COLORS = {
    'yellow': 'yellow',
    'red': 'red',
    'blue': 'blue',
    'green': 'green',
    'rainbow': 'rainbow',
}

GILD_SIZE = 78

ARMORY = {
    'backpacks': {
        'id': 'backpacks',
        'icon': 'dsdultra/assets/icons/groups/Backpack.png',
        'full': True,
        'name': 'Backpacks',
        'color': 'blue',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'backpack_jump': {
                'id': 'backpack_jump',
                'name': 'LIFT-850 Jump Pack',
                'icon': 'dsdultra/assets/png/Hangar/Jump Pack.png',
                'code': ['down', 'up', 'up', 'down', 'up'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_hover': {
                'id': 'backpack_hover',
                'name': 'LIFT-860 Hover Pack',
                'icon': 'dsdultra/assets/png/Borderline Justice/Hover Pack.png',
                'code': ['down', 'left', 'right', 'down', 'left', 'right'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_warp': {
                'id': 'backpack_warp',
                'name': 'LIFT-182 Warp Pack',
                'icon': 'dsdultra/assets/png/Control Group/Warp Pack.png',
                'code': ['down', 'up', 'up', 'down', 'left', 'right'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_supply': {
                'id': 'backpack_supply',
                'name': 'B-1 Supply Pack',
                'icon': 'dsdultra/assets/png/Engineering Bay/Supply Pack.png',
                'code': ['down', 'left', 'down', 'up', 'up', 'down'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_hellbomb': {
                'id': 'backpack_hellbomb',
                'name': 'B-100 Portable Hellbomb ',
                'icon': 'dsdultra/assets/png/Servants of Freedom/Hellbomb Portable.png',
                'code': ['down', 'right', 'up', 'up', 'up'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_ballistic_shield': {
                'id': 'backpack_ballistic_shield',
                'name': 'SH-20 Ballistic Shield Backpack',
                'icon': 'dsdultra/assets/png/Engineering Bay/Ballistic Shield Backpack.png',
                'code': ['down', 'left', 'down', 'down', 'up', 'left'],
                'color': 'blue',
                'cooldown': 300,
            },
            'backpack_shield_generator': {
                'id': 'backpack_shield_generator',
                'name': 'SH-32 Shield Generator Pack',
                'icon': 'dsdultra/assets/png/Engineering Bay/Shield Generator Pack.png',
                'code': ['down', 'up', 'left', 'right', 'left', 'right'],
                'color': 'blue',
                'cooldown': 0,
            },
            'backpack_directional_shield': {
                'id': 'backpack_directional_shield',
                'name': 'SH-51 Directional Shield ',
                'icon': 'dsdultra/assets/png/Urban Legends/Directional Shield.png',
                'code': ['down', 'up', 'left', 'right', 'up', 'up'],
                'color': 'blue',
                'cooldown': 0,
            },
            'backpack_guard_dog': {
                'id': 'backpack_guard_dog',
                'name': 'AX/AR-23 "Guard Dog"',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Guard Dog.png',
                'code': ['down', 'up', 'left', 'up', 'right', 'down'],
                'color': 'blue',
                'cooldown': 300,
            },
            'backpack_guard_dog_rover': {
                'id': 'backpack_guard_dog_rover',
                'name': 'AX/LAS-5 "Guard Dog" Rover',
                'icon': 'dsdultra/assets/png/Engineering Bay/Guard Dog Rover.png',
                'code': ['down', 'up', 'left', 'up', 'right', 'right'],
                'color': 'blue',
                'cooldown': 300,
            },
            'backpack_guard_dog_dog_breath': {
                'id': 'backpack_guard_dog_dog_breath',
                'name': 'AX/TX-13 "Guard Dog" Dog Breath',
                'icon': 'dsdultra/assets/png/Chemical Agents/Guard Dog Breath.png',
                'code': ['down', 'up', 'left', 'up', 'right', 'up'],
                'color': 'blue',
                'cooldown': 480,
            },
            'backpack_guard_dog_k9': {
                'id': 'backpack_guard_dog_k9',
                'name': 'AX/ARC-3 "Guard Dog" K-9',
                'icon': 'dsdultra/assets/png/Force of Law/Guard Dog K-9.png',
                'code': ['down', 'up', 'left', 'up', 'right', 'left'],
                'color': 'blue',
                'cooldown': 480,
            },
        }
    },
    'weapons': {
        'id': 'weapons',
        'icon': 'dsdultra/assets/icons/groups/Weapons.png',
        'full': True,
        'name': 'Weapons',
        'color': 'blue',
        'content_class': 'dsdultra.buttons.group.ButtonGroup',
        'content': {
            'weapons_backpack': {
                'id': 'weapons_backpack',
                'icon': 'dsdultra/assets/icons/groups/Backpack.png',
                'icon_size': 50,
                'full': True,
                'name': 'Weapons',
                'color': 'blue',
                'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
                'content': {
                    'weapon_recoilless_rifle': {
                        'id': 'weapon_recoilless_rifle',
                        'name': 'GR-8 Recoilless Rifle',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Recoilless Rifle.png',
                        'code': ['down', 'left', 'right', 'right', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_airburst_rocket': {
                        'id': 'weapon_airburst_rocket',
                        'name': 'RL-77 Airburst Rocket Launcher',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Airburst Rocket Launcher.png',
                        'code': ['down', 'up', 'up', 'left', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_autocannon': {
                        'id': 'weapon_autocannon',
                        'name': 'AC-8 Autocannon',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Autocannon.png',
                        'code': ['down', 'left', 'down', 'up', 'up', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_spear': {
                        'id': 'weapon_spear',
                        'name': 'FAF-14 Spear',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Spear.png',
                        'code': ['down', 'down', 'up', 'down', 'down'],
                        'cooldown': 0,
                    },
                    'weapon_wasp': {
                        'id': 'weapon_wasp',
                        'name': 'StA-X3 W.A.S.P. Launcher',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/StA-X3 W.A.S.P. Launcher.png',
                        'code': ['down', 'down', 'up', 'down', 'right'],
                        'cooldown': 0,
                    },
                },
            },
            'weapons_standalone': {
                'id': 'weapons_standalone',
                'icon': 'dsdultra/assets/icons/groups/No Backpack.png',
                'full': True,
                'name': 'Weapons',
                'color': 'blue',
                'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
                'content': {
                    'weapon_stalwart': {
                        'id': 'weapon_stalwart',
                        'name': 'M-105 Stalwart',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Stalwart.png',
                        'code': ['down', 'left', 'down', 'up', 'up', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_machine_gun': {
                        'id': 'weapon_machine_gun',
                        'name': 'MG-43 Machine Gun',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Machine Gun.png',
                        'code': ['down', 'left', 'down', 'up', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_heavy_machine_gun': {
                        'id': 'weapon_heavy_machine_gun',
                        'name': 'MG-206 Heavy Machine Gun',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Heavy Machine Gun.png',
                        'code': ['down', 'left', 'up', 'down', 'down'],
                        'cooldown': 0,
                    },
                    'weapon_anti_materiel_rifle': {
                        'id': 'weapon_anti_materiel_rifle',
                        'name': 'APW-1 Anti-Materiel Rifle',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Anti-Materiel Rifle.png',
                        'code': ['down', 'left', 'right', 'up', 'down'],
                        'cooldown': 0,
                    },
                    'weapon_flamethrower': {
                        'id': 'weapon_flamethrower',
                        'name': 'FLAM-40 Flamethrower',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Flamethrower.png',
                        'code': ['down', 'left', 'up', 'down', 'up'],
                        'cooldown': 0,
                    },
                    'weapon_sterilizer': {
                        'id': 'weapon_sterilizer',
                        'name': 'TX-41 Sterilizer ',
                        'icon': 'dsdultra/assets/png/Chemical Agents/Sterilizer.png',
                        'code': ['down', 'left', 'up', 'down', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_grenade_launcher': {
                        'id': 'weapon_grenade_launcher',
                        'name': 'GL-21 Grenade Launcher',
                        'icon': 'dsdultra/assets/png/Engineering Bay/Grenade Launcher.png',
                        'code': ['down', 'left', 'up', 'left', 'down'],
                        'cooldown': 0,
                    },
                    'weapon_grenade_launcher_arc': {
                        'id': 'weapon_grenade_launcher_arc',
                        'name': 'GL-52 De-Escalator',
                        'icon': 'dsdultra/assets/png/Force of Law/GL-52 De-Escalator.png',
                        'code': ['down', 'right', 'up', 'left', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_flag': {
                        'id': 'weapon_flag',
                        'name': 'CQC-1 One True Flag',
                        'icon': 'dsdultra/assets/png/Masters of Ceremony/One True Flag.png',
                        'code': ['down', 'left', 'right', 'right', 'up'],
                        'cooldown': 0,
                    },
                    'weapon_epoch': {
                        'id': 'weapon_epoch',
                        'name': 'PLAS-45 Epoch',
                        'icon': 'dsdultra/assets/png/Control Group/Epoch.png',
                        'code': ['down', 'left', 'up', 'left', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_railgun': {
                        'id': 'weapon_railgun',
                        'name': 'RS-422 Railgun',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Railgun.png',
                        'code': ['down', 'right', 'up', 'down', 'left', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_speargun': {
                        'id': 'weapon_speargun',
                        'name': 'S-11 Speargun',
                        'icon': 'dsdultra/assets/png/Dust Devils/Speargun.png',
                        'code': ['down', 'right', 'down', 'left', 'up', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_silo': {
                        'id': 'weapon_silo',
                        'name': 'MS-11 Solo Silo ',
                        'icon': 'dsdultra/assets/png/Dust Devils/Solo Silo.png',
                        'code': ['down', 'up', 'right', 'down', 'down'],
                        'cooldown': 0,
                    },
                },
            },
            'weapons_disposable': {
                'id': 'weapons_disposable',
                'icon': 'dsdultra/assets/icons/groups/Disposable.png',
                'full': True,
                'name': 'Weapons',
                'color': 'blue',
                'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
                'content': {
                    'weapon_eat': {
                        'id': 'weapon_eat',
                        'name': 'EAT-17 Expendable Anti-Tank ',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Expendable Anti-Tank.png',
                        'code': ['down', 'down', 'left', 'up', 'right'],
                        'cooldown': 0,
                    },
                    'weapon_expendable_napalm': {
                        'id': 'weapon_expendable_napalm',
                        'name': 'EAT-700 Expendable Napalm',
                        'icon': 'dsdultra/assets/png/Dust Devils/Expendable Napalm.png',
                        'code': ['down', 'down', 'left', 'up', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_commando': {
                        'id': 'weapon_commando',
                        'name': 'MLS-4X Commando',
                        'icon': 'dsdultra/assets/png/Patriotic Administration Center/Commando.png',
                        'code': ['down', 'left', 'up', 'down', 'right'],
                        'cooldown': 0,
                    },
                },
            },
            'weapons_energy': {
                'id': 'weapons_energy',
                'icon': 'dsdultra/assets/icons/groups/Energy.png',
                'full': True,
                'name': 'Weapons',
                'color': 'blue',
                'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
                'content': {
                    'weapon_arc_thrower': {
                        'id': 'weapon_arc_thrower',
                        'name': 'ARC-3 Arc Thrower',
                        'icon': 'dsdultra/assets/png/Engineering Bay/Arc Thrower.png',
                        'code': ['down', 'right', 'up', 'down', 'left', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_laser': {
                        'id': 'weapon_laser',
                        'name': 'LAS-98 Laser Cannon',
                        'icon': 'dsdultra/assets/png/Engineering Bay/Laser Cannon.png',
                        'code': ['down', 'left', 'down', 'up', 'left'],
                        'cooldown': 0,
                    },
                    'weapon_quasar': {
                        'id': 'weapon_quasar',
                        'name': 'LAS-99 Quasar Cannon',
                        'icon': 'dsdultra/assets/png/Engineering Bay/Quasar Cannon.png',
                        'code': ['down', 'down', 'up', 'left', 'right'],
                        'cooldown': 0,
                    },
                },
            },
        }
    },
    'vehicles': {
        'id': 'vehicles',
        'icon': 'dsdultra/assets/icons/groups/Vehicle.png',
        'full': True,
        'name': 'Vehicles',
        'color': 'blue',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'vehicle_exosuit_patriot': {
                'id': 'vehicle_exosuit_patriot',
                'name': 'EXO-45 Patriot Exosuit',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Patriot Exosuit.png',
                'code': ['left', 'down', 'right', 'up', 'left', 'down', 'down'],
                'cooldown': 0,
            },
            'vehicle_exosuit_emancipator': {
                'id': 'vehicle_exosuit_emancipator',
                'name': 'EXO-49 Emancipator Exosuit',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Emancipator Exosuit.png',
                'code': ['left', 'down', 'right', 'up', 'left', 'down', 'up'],
                'cooldown': 0,
            },
            'vehicle_frv': {
                'id': 'vehicle_frv',
                'name': 'EXO-45 Patriot Exosuit ',
                'icon': 'dsdultra/assets/png/Hangar/Fast Recon Vehicle.png',
                'code': ['left', 'down', 'right', 'down', 'right', 'down', 'up'],
                'cooldown': 0,
            },
        }
    },
    'orbitals': {
        'id': 'orbitals',
        'icon': 'dsdultra/assets/icons/groups/Orbital.png',
        'full': True,
        'name': 'Orbitals',
        'color': 'red',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'orbital_precision_strike': {
                'id': 'orbital_precision_strike',
                'name': 'Orbital Precision Strike',
                'icon': 'dsdultra/assets/png/Bridge/Orbital Precision Strike.png',
                'color': 'red',
                'code': ['right', 'right', 'up'],
                'cooldown': 0,
            },
            'orbital_gatling_barrage': {
                'id': 'orbital_gatling_barrage',
                'name': 'Orbital Gatling Barrage',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Gatling Barrage.png',
                'color': 'red',
                'code': ['right', 'down', 'left', 'up', 'up'],
                'cooldown': 0,
            },
            'orbital_airburst_strike': {
                'id': 'orbital_airburst_strike',
                'name': 'Orbital Airburst Strike',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Airburst Strike.png',
                'color': 'red',
                'code': ['right', 'right', 'right'],
                'cooldown': 0,
            },
            'orbital_120mm_he_barrage': {
                'id': 'orbital_120mm_he_barrage',
                'name': 'Orbital 120mm HE Barrage',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital 120MM HE Barrage.png',
                'color': 'red',
                'code': ['right', 'right', 'down', 'left', 'right', 'down'],
                'cooldown': 0,
            },
            'orbital_380mm_he_barrage': {
                'id': 'orbital_380mm_he_barrage',
                'name': 'Orbital 380mm HE Barrage',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital 380MM HE Barrage.png',
                'color': 'red',
                'code': ['right', 'down', 'up', 'up', 'left', 'down', 'down'],
                'cooldown': 0,
            },
            'orbital_walking_barrage': {
                'id': 'orbital_walking_barrage',
                'name': 'Orbital Walking Barrage',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Walking Barrage.png',
                'color': 'red',
                'code': ['right', 'down', 'right', 'down', 'right', 'down'],
                'cooldown': 0,
            },
            'orbital_laser': {
                'id': 'orbital_laser',
                'name': 'Orbital Laser',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Laser.png',
                'color': 'red',
                'code': ['right', 'down', 'up', 'right', 'down', 'up'],
                'cooldown': 0,
            },
            'orbital_railcannon_strike': {
                'id': 'orbital_railcannon_strike',
                'name': 'Orbital Railcannon Strike',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Railcannon Strike.png',
                'color': 'red',
                'code': ['right', 'up', 'down', 'down', 'right'],
                'cooldown': 0,
            },
            'orbital_gas_strike': {
                'id': 'orbital_gas_strike',
                'name': 'Orbital Gas Strike',
                'icon': 'dsdultra/assets/png/Bridge/Orbital Gas Strike.png',
                'color': 'red',
                'code': ['right', 'right', 'down', 'right'],
                'cooldown': 0,
            },
            'orbital_ems_strike': {
                'id': 'orbital_ems_strike',
                'name': 'Orbital EMS Strike',
                'icon': 'dsdultra/assets/png/Bridge/Orbital EMS Strike.png',
                'color': 'red',
                'code': ['right', 'right', 'left', 'down'],
                'cooldown': 0,
            },
            'orbital_smoke_strike': {
                'id': 'orbital_smoke_strike',
                'name': 'Orbital Smoke Strike',
                'icon': 'dsdultra/assets/png/Bridge/Orbital Smoke Strike.png',
                'color': 'red',
                'code': ['right', 'right', 'down', 'up'],
                'cooldown': 0,
            },
            'orbital_napalm_barrage': {
                'id': 'orbital_napalm_barrage',
                'name': 'Orbital Napalm Barrage',
                'icon': 'dsdultra/assets/png/Orbital Cannons/Orbital Napalm Barrage.png',
                'color': 'red',
                'code': ['right', 'down', 'left', 'down', 'up'],
                'cooldown': 0,
            },
        }
    },
    'eagles': {
        'id': 'eagles',
        'icon': 'dsdultra/assets/icons/groups/Eagle.png',
        'full': True,
        'name': 'Eagles',
        'color': 'red',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'eagle_strafing_run': {
                'id': 'eagle_strafing_run',
                'name': 'Eagle Strafing Run',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Strafing Run.png',
                'color': 'red',
                'code': ['up', 'right', 'right'],
                'cooldown': 0,
            },
            'eagle_airstrike': {
                'id': 'eagle_airstrike',
                'name': 'Eagle Airstrike',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Airstrike.png',
                'color': 'red',
                'code': ['up', 'right', 'down', 'right'],
                'cooldown': 0,
            },
            'eagle_cluster_bomb': {
                'id': 'eagle_cluster_bomb',
                'name': 'Eagle Cluster Bomb',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Cluster Bomb.png',
                'color': 'red',
                'code': ['up', 'right', 'down', 'down', 'right'],
                'cooldown': 0,
            },
            'eagle_napalm_airstrike': {
                'id': 'eagle_napalm_airstrike',
                'name': 'Eagle Napalm Airstrike',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Napalm Airstrike.png',
                'color': 'red',
                'code': ['up', 'right', 'down', 'up'],
                'cooldown': 0,
            },
            'eagle_smoke_strike': {
                'id': 'eagle_smoke_strike',
                'name': 'Eagle Smoke Strike',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Smoke Strike.png',
                'color': 'red',
                'code': ['up', 'right', 'up', 'down'],
                'cooldown': 0,
            },
            'eagle_110mm_rocket_pods': {
                'id': 'eagle_110mm_rocket_pods',
                'name': 'Eagle 110mm Rocket Pods',
                'icon': 'dsdultra/assets/png/Hangar/Eagle 110MM Rocket Pods.png',
                'color': 'red',
                'code': ['up', 'right', 'up', 'down'],
                'cooldown': 0,
            },
            'eagle_500kg_bomb': {
                'id': 'eagle_500kg_bomb',
                'name': 'Eagle 500kg Bomb',
                'icon': 'dsdultra/assets/png/Hangar/Eagle 500KG Bomb.png',
                'color': 'red',
                'code': ['up', 'right', 'down', 'down', 'down'],
                'cooldown': 0,
            },
        }
    },
    'mines': {
        'id': 'mines',
        'icon': 'dsdultra/assets/icons/groups/Mines.png',
        'full': True,
        'name': 'Mines',
        'color': 'green',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'mine_antipersonnel': {
                'id': 'mine_antipersonnel',
                'name': 'MD-6 Anti-Personnel Minefield',
                'icon': 'dsdultra/assets/png/Engineering Bay/Anti-Personnel Minefield.png',
                'color': 'green',
                'code': ['down', 'left', 'up', 'right'],
                'cooldown': 120,
            },
            'mine_incendiary': {
                'id': 'mine_incendiary',
                'name': 'MD-I4 Incendiary Mines',
                'icon': 'dsdultra/assets/png/Engineering Bay/Incendiary Mines.png',
                'color': 'green',
                'code': ['down', 'left', 'left', 'down'],
                'cooldown': 0,
            },
            'mine_gas': {
                'id': 'mine_gas',
                'name': 'MD-8 Gas Mines',
                'icon': 'dsdultra/assets/png/Engineering Bay/Gas Mine.png',
                'color': 'green',
                'code': ['down', 'left', 'left', 'right'],
                'cooldown': 120,
            },
            'mine_antitank': {
                'id': 'mine_antitank',
                'name': 'MD-17 Anti-Tank Mines',
                'icon': 'dsdultra/assets/png/Engineering Bay/Anti-Tank Mines.png',
                'color': 'green',
                'code': ['down', 'left', 'up', 'up'],
                'cooldown': 0,
            },
            'tower_tesla': {
                'id': 'tower_tesla',
                'name': 'A/ARC-3 Tesla Tower',
                'icon': 'dsdultra/assets/png/Bridge/Tesla Tower.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'up', 'left', 'right'],
                'cooldown': 0,
            },
            'tower_shield': {
                'id': 'tower_shield',
                'name': 'FX-12 Shield Generator Relay',
                'icon': 'dsdultra/assets/png/Bridge/Shield Generator Relay.png',
                'color': 'green',
                'code': ['down', 'down', 'left', 'right', 'left', 'right'],
                'cooldown': 0,
            },
        }
    },
    'sentries': {
        'id': 'sentries',
        'icon': 'dsdultra/assets/icons/groups/Sentry.png',
        'full': True,
        'name': 'Sentries',
        'color': 'green',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'sentry_machine_gun': {
                'id': 'sentry_machine_gun',
                'name': 'A/MG-43 Machine Gun Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Machine Gun Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'right', 'up'],
                'cooldown': 180,
            },
            'sentry_gatling': {
                'id': 'sentry_gatling',
                'name': 'A/G-16 Gatling Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Gatling Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'left'],
                'cooldown': 180,
            },
            'sentry_mortar': {
                'id': 'sentry_mortar',
                'name': 'A/M-12 Mortar Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Mortar Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'right', 'down'],
                'cooldown': 180,
            },
            'sentry_autocannon': {
                'id': 'sentry_autocannon',
                'name': 'A/AC-8 Autocannon Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Autocannon Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'up', 'left', 'up'],
                'cooldown': 180,
            },
            'sentry_rocket': {
                'id': 'sentry_rocket',
                'name': 'A/MLS-4X Rocket Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/Rocket Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'right', 'left'],
                'cooldown': 180,
            },
            'sentry_ems_mortar': {
                'id': 'sentry_ems_mortar',
                'name': 'A/M-23 EMS Mortar Sentry',
                'icon': 'dsdultra/assets/png/Robotics Workshop/EMS Mortar Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'down', 'right'],
                'cooldown': 180,
            },
            'sentry_laser': {
                'id': 'sentry_laser',
                'name': 'A/LAS-98 Laser Sentry',
                'icon': 'dsdultra/assets/png/Control Group/Laser Sentry.png',
                'color': 'green',
                'code': ['down', 'down', 'left', 'down', 'up', 'up', 'left'],
                'cooldown': 162,
            },
            'sentry_flame': {
                'id': 'sentry_flame',
                'name': 'A/FLAM-40 Flame Sentry',
                'icon': 'dsdultra/assets/png/Urban Legends/Flame Sentry.png',
                'color': 'green',
                'code': ['down', 'up', 'right', 'down', 'up', 'up'],
                'cooldown': 162,
            },
        }
    },
    'emplacement': {
        'id': 'emplacement',
        'icon': 'dsdultra/assets/icons/groups/Emplacement.png',
        'full': True,
        'name': 'Mines',
        'color': 'green',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'emplacement_hmg': {
                'id': 'emplacement_hmg',
                'name': 'E/MG-101 HMG Emplacement',
                'icon': 'dsdultra/assets/png/Bridge/HMG Emplacement.png',
                'color': 'green',
                'code': ['down', 'up', 'left', 'right', 'right', 'left'],
                'cooldown': 0,
            },
            'emplacement_antitank': {
                'id': 'emplacement_antitank',
                'name': 'E/AT-12 Anti-Tank Emplacement',
                'icon': 'dsdultra/assets/png/Urban Legends/Anti-Tank Emplacement.png',
                'color': 'green',
                'code': ['down', 'up', 'left', 'right', 'right', 'right'],
                'cooldown': 0,
            },
            'battlement_grenadier': {
                'id': 'battlement_grenadier',
                'name': 'E/GL-21 Grenadier Battlement',
                'icon': 'dsdultra/assets/png/Bridge/Grenadier Battlement.png',
                'color': 'green',
                'code': ['down', 'right', 'down', 'left', 'right'],
                'cooldown': 0,
            },
        }
    },
    'common': {
        'id': 'common',
        'icon': 'dsdultra/assets/icons/groups/Generic.png',
        'full': True,
        'name': 'Common',
        'color': 'yellow',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'common_reinforce': {
                'id': 'common_reinforce',
                'name': 'Reinforce',
                'icon': 'dsdultra/assets/png/General Stratagems/Reinforce.png',
                'color': 'yellow',
                'code': ['up', 'down', 'right', 'left', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'common_resupply': {
                'id': 'common_resupply',
                'name': 'Resupply',
                'icon': 'dsdultra/assets/png/General Stratagems/Resupply.png',
                'color': 'yellow',
                'code': ['down', 'down', 'up', 'right'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'common_eagle_rearm': {
                'id': 'common_eagle_rearm',
                'name': 'Eagle Rearm',
                'icon': 'dsdultra/assets/png/Hangar/Eagle Rearm.png',
                'color': 'yellow',
                'code': ['up', 'up', 'left', 'up', 'right'],
                'cooldown': 0,
            },
            'common_sos': {
                'id': 'common_sos',
                'name': 'SOS Beacon',
                'icon': 'dsdultra/assets/png/General Stratagems/SOS Beacon.png',
                'color': 'yellow',
                'code': ['up', 'down', 'right', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
        }
    },
    'mission': {
        'id': 'mission',
        'icon': 'dsdultra/assets/png/General Stratagems/Super Earth Flag.png',
        'icon_size': GILD_SIZE,
        'full': True,
        'name': 'Generic',
        'color': 'yellow',
        'content_class': 'dsdultra.buttons.stratagem.ButtonStratagem',
        'content': {
            'mission_seaf': {
                'id': 'mission_seaf',
                'name': 'SEAF Artillery',
                'icon': 'dsdultra/assets/png/General Stratagems/SEAF Artillery.png',
                'color': 'yellow',
                'code': ['right', 'up', 'up', 'down'],
                'cooldown': 0,
            },
            'mission_hellbomb': {
                'id': 'mission_hellbomb',
                'name': 'Hellbomb',
                'icon': 'dsdultra/assets/png/General Stratagems/Hellbomb.png',
                'color': 'yellow',
                'code': ['down', 'up', 'left', 'down', 'up', 'right', 'down', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_flag': {
                'id': 'mission_flag',
                'name': 'Super Earth Flag',
                'icon': 'dsdultra/assets/png/General Stratagems/Super Earth Flag.png',
                'color': 'yellow',
                'code': ['down', 'up', 'down', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_sssd': {
                'id': 'mission_sssd',
                'name': 'SSSD Delivery',
                'icon': 'dsdultra/assets/png/General Stratagems/Upload Data.png',
                'color': 'yellow',
                'code': ['down', 'down', 'down', 'up', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_upload': {
                'id': 'mission_upload',
                'name': 'Upload Data',
                'icon': 'dsdultra/assets/png/General Stratagems/Upload Data.png',
                'color': 'yellow',
                'code': ['left', 'right', 'up', 'up', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_seismic_probe': {
                'id': 'mission_seismic_probe',
                'name': 'Seismic Probe',
                'icon': 'dsdultra/assets/png/General Stratagems/Seismic Probe.png',
                'color': 'yellow',
                'code': ['up', 'up', 'left', 'right', 'down', 'down'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_dark_fluid': {
                'id': 'mission_dark_fluid',
                'name': 'Dark Fluid Vessel',
                'icon': 'dsdultra/assets/png/General Stratagems/Dark Fluid Vessel.png',
                'color': 'yellow',
                'code': ['up', 'left', 'right', 'down', 'up', 'up'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_drill_prospecting': {
                'id': 'mission_drill_prospecting',
                'name': 'Prospecting Drill',
                'icon': 'dsdultra/assets/png/General Stratagems/Prospecting Drill.png',
                'color': 'yellow',
                'code': ['down', 'down', 'left', 'right', 'down', 'down'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_drill_tectonic': {
                'id': 'mission_drill_tectonic',
                'name': 'Tectonic Drill',
                'icon': 'dsdultra/assets/png/General Stratagems/Tectonic Drill.png',
                'color': 'yellow',
                'code': ['up', 'down', 'up', 'down', 'up', 'down'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_drill_hive': {
                'id': 'mission_drill_hive',
                'name': 'Hive Breaker Drill',
                'icon': 'dsdultra/assets/png/General Stratagems/Hive Breaker Drill.png',
                'color': 'yellow',
                'code': ['left', 'up', 'down', 'right', 'down', 'down'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
            'mission_orbital_illumination_flare': {
                'id': 'mission_orbital_illumination_flare',
                'name': 'Orbital Illumination Flare',
                'icon': 'dsdultra/assets/png/General Stratagems/Orbital Illumination Flare.png',
                'color': 'yellow',
                'code': ['right', 'right', 'left', 'left'],
                'cooldown': 0,
                'icon_size': GILD_SIZE,
            },
        }
    },
}
